<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net7.0</TargetFramework>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Discord.Net" Version="3.15.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="7.0.13" />
		<PackageReference Include="RestSharp" Version="111.4.1" />
		<PackageReference Include="Serilog" Version="*" />
		<PackageReference Include="Serilog.Sinks.Console" Version="*" />
		<PackageReference Include="Serilog.Sinks.File" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<None Update=".gitignore">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
			<TargetPath>path\to\output\directory\.gitignore</TargetPath>
		</None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="logs\" />
	</ItemGroup>

</Project>
